services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: productsdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U appuser -d productsdb"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  pgdata:
